DROP TABLE IF EXISTS USER;

CREATE TABLE USER
(
  USER_ID     VARCHAR(20) NOT NULL PRIMARY KEY,
  USER_TYPE   INT NOT NULL,
  USER_LEVEL  INT NOT NULL,
  LOG_IN_NUM  INT NOT NULL,
  LAST_LOGIN_DATE TIMESTAMP DEFAULT NOW(),
  PASSWORD    VARCHAR(256) NOT NULL,
  FULL_NAME   VARCHAR(30) NOT NULL,
  EMAIL       VARCHAR(30),
  DATE_CREATED  TIMESTAMP DEFAULT NOW(),
  ADDR_ID     INT NOT NULL,
  USER_IDX    INT(11) DEFAULT NULL,
  FOREIGN KEY (ADDR_ID) REFERENCES PARENT(ADDR_ID)
);

DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS
(
  ADDR_ID       INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ADDR_STREET   VARCHAR(40) NOT NULL,
  ADDR_CITY     VARCHAR(20) NOT NULL,
  ADDR_STATE    VARCHAR(3) NOT NULL,
  ADDR_ZIP_CODE VARCHAR(4) NOT NULL
);


